### ISSUE TITLE
Request for Release of mdadm Version 4.4

### ISSUE THREAD

**Issue by haobinnan** [md-raid-utilities/mdadm#131]
Since version 4.3, many issues have been addressed in mdadm. Would it be possible to release a new version 4.4 that includes these improvements and fixes?

**Comment by mtkaczyk** [comment]
It is processing:
https://github.com/md-raid-utilities/mdadm/pull/119

I need to wait little more for Kuai's patches for removing bitmap file support. This activity can be tracked on ML:
https://lore.kernel.org/linux-raid/20241120064637.3657385-1-yukuai1@huaweicloud.com/T/#t

Right now, I'm not merging risky changes, that is why we have so many PRs open. I you would like support us with releasing new version you can test latest upstream on your own and let me know if you see regressions.

As you will see in the mentioned PR description, we have hard times here. It is hard for me to keep focus on release now and I cannot promise you any date yet.

**Comment by mtkaczyk** [comment]
I would like to make it done by the end of December for sure.

**Comment by haobinnan** [comment]
> I would like to make it done by the end of December for sure.

Thank you for your quick response!
