### ISSUE TITLE
Dead code in super1.c

### ISSUE THREAD

**Issue by ncroxon** [md-raid-utilities/mdadm#22]
One line of dead code in super1.c `space = UINT16_MAX;`.

Event cond_at_least: | Condition "space < 16", taking false branch. Now the value of "space" is at least 16.

1448 			`if (space < (PPL_HEADER_SIZE >> 9) + 8) {`
1449 				`pr_err("Not enough space to add ppl\n");`
1450 				`return -2;`
1451 			`}`

Event cond_between: | Condition "space >= 2048", taking false branch. Now the value of "space" is between 16 and 2047.

1453 			`if (space >= (MULTIPLE_PPL_AREA_SIZE_SUPER1 >> 9)) {`
1454 				`space = (MULTIPLE_PPL_AREA_SIZE_SUPER1 >> 9);`
1455 			`} else {`
1456 				`int optimal_space = choose_ppl_space(`
1457 							`__le32_to_cpu(sb->chunksize));`

Event cond_at_most:	Condition "space > optimal_space", taking true branch. Now the value of "optimal_space" is at most 2046.

1458 				`if (space > optimal_space)`

Event assignment:	Assigning: "space" = "optimal_space".

1459 					`space = optimal_space;`

Event at_most:	At condition "space > 65535", the value of "space" must be at most 2047.
Event dead_error_condition:	The condition "space > 65535" cannot be true.

1460 				`if (space > UINT16_MAX)`

Event dead_error_line:	Execution cannot reach this statement: "space = 65535;".

1461 					`space = UINT16_MAX;`

**Comment by mtkaczyk** [comment]
Hi @ncroxon 
Are you going to work on it?
