### ISSUE TITLE
historic information in manual pages

### ISSUE THREAD

**Issue by Zugschlus** [md-raid-utilities/mdadm#82]
Hi,

the manpages in the package elaborate quite a bit about which features got added in the 2.6 and 3.0 kernel times. Since mdadm officially does not support running on kernels earlier than 3.10 any more, this information is only of interest for archeologists.

Would you be willing to accept a patch that removes such references and changes the man page to just state that those options are available without documenting when they got added? I won't touch any references that might be helpful/important for people still using ancient arrays though. This should be debated on the mailing list.

I will do a PR in due time once you have indicated that it has a chance of being applied.

Greetings
Marc

**Comment by mtkaczyk** [comment]
Hey @Zugschlus
Sure, do PR here or sent patch through ML. 
It is said that nothing lover than kernel 3.10 is supported so I'm open to reject these references. Simply, I didn't manage time to do it :(

Thanks!
